# Generated by Django 3.2.8 on 2021-10-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='body',
            field=models.TextField(default='Paxi haleko hai'),
            preserve_default=False,
        ),
    ]
